before:
  hooks:
    - go mod tidy
builds:
  - id: "redis-web-manager"
    binary: RWM
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.GIN_MODE=release
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

dockers:
  - 
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/slowrookie/redis-web-manager:{{ .Tag }}"
      - "docker.io/slowrookie/redis-web-manager:latest"
    skip_push: auto
    dockerfile: Dockerfile