before:
  hooks:
    - go mod tidy
builds:
  - id: "redis-web-manager"
    binary: RedisWebManager
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.MODE=release
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

#dockers:
#  -
#    goos: linux
#    goarch: amd64
#    image_templates:
#      - "docker.io/slowrookie/redis-web-manager:{{ .Tag }}"
#      - "docker.io/slowrookie/redis-web-manager:latest"
#    skip_push: false
#    dockerfile: Dockerfile

dockers:
  - image_templates:
      - "docker.io/massinger/redis-web-manager:{{ .Tag }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "docker.io/slowrookie/redis-web-manager:{{ .Tag }}-arm64v8"
    goos: linux
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: docker.io/massinger/redis-web-manager:latest
    image_templates:
      - docker.io/massinger/redis-web-manager:{{ .Tag }}-amd64
      - docker.io/massinger/redis-web-manager:{{ .Tag }}-arm64v8
