name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # yarn cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # yarn build
      - uses: borales/actions-yarn@v2.3.0
      - run: |
          cd ./web
          yarn install
          yarn run build
      # upload
      - name: Upload frontend build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: ./web/build

  platform-build:
    strategy:
      matrix:
        go-version: [1.17.6]
        # platform: [macos-latest]
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{matrix.platform}}
    needs: frontend-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
          echo ::set-output name=COMMIT::$(echo $GITHUB_SHA)
          echo ::set-output name=DATE::$(date +'%Y-%m-%d')
      - name: Download frontend build
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact
          path: ./web/build
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
      - run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build package osx
        run: |
          # wails doctor
          wails build -s -ldflags '-s -w -X main.version=${{ steps.get_version.outputs.VERSION }} -X main.commit=${{ steps.get_version.outputs.COMMIT}} -X main.date={{steps.get_version.outputs.DATE}} -X main.builtBy=GithubActions -X main.GIN_MODE=release'
          ls -lh ./build/bin/redis-web-manager.app/Contents/MacOS
          # truning .app to .dmg
          npm install -g appdmg
          appdmg dmg-spec.json redis-web-manager_darwin_amd64.dmg
        if: matrix.platform == 'macos-latest'
      - name: Build package linux
        run: |
          sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
          # wails doctor
          wails build -s -ldflags '-s -w -X main.version=${{ steps.get_version.outputs.VERSION }} -X main.commit=${{ steps.get_version.outputs.COMMIT}} -X main.date={{steps.get_version.outputs.DATE}} -X main.builtBy=GithubActions -X main.GIN_MODE=release'
          # turn into app image
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage
          ./linuxdeploy*.AppImage --appdir AppDir --executable ./build/bin/redis-web-manager --desktop-file=redis-web-manager.AppImage.desktop --icon-file=appicon_64x64.png --output appimage
          ls ./
          cp Redis_Web_Manager-*.AppImage ./redis-web-manager_x86_64.AppImage
        if: matrix.platform == 'ubuntu-latest'
      - name: Build package windows
        run: |
          # wails doctor
          wails build -s -ldflags '-s -w -X main.version=${{ steps.get_version.outputs.VERSION }} -X main.commit=${{ steps.get_version.outputs.COMMIT}} -X main.date={{steps.get_version.outputs.DATE}} -X main.builtBy=GithubActions -X main.GIN_MODE=release'
          dir
          copy build/bin/redis-web-manager.exe build/bin/redis-web-manager_x86_64.exe
        if: matrix.platform == 'windows-latest'

      - name: Upload artifact osx
        uses: actions/upload-artifact@v2
        with:
          name: redis-web-manager_darwin_amd64.dmg
          path: redis-web-manager_darwin_amd64.dmg
        if: matrix.platform == 'macos-latest'
      - name: Upload artifact linux
        uses: actions/upload-artifact@v2
        with:
          name: redis-web-manager_x86_64.AppImage
          path: redis-web-manager_x86_64.AppImage
        if: matrix.platform == 'ubuntu-latest'
      - name: Upload artifact windows
        uses: actions/upload-artifact@v2
        with:
          name: redis-web-manager_x86_64.exe
          path: build/bin/redis-web-manager_x86_64.exe
        if: matrix.platform == 'windows-latest'

  release:
    runs-on: ubuntu-latest
    needs: platform-build
    steps:
      - name: Download artifact osx
        uses: actions/download-artifact@v2
        with:
          name: redis-web-manager_darwin_amd64.dmg
          path: ./bin/
      - name: Download artifact linx
        uses: actions/download-artifact@v2
        with:
          name: redis-web-manager_x86_64.AppImage
          path: ./bin/
      - name: Download artifact windows
        uses: actions/download-artifact@v2
        with:
          name: redis-web-manager_x86_64.exe
          path: ./bin/
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./bin/**


  # goreleaser:
  #   runs-on: ubuntu-latest
  #   needs: build-frontend
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Download frontend build
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: frontend-artifact
  #         path: ./web/build

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.17.6
  #     - run: |
  #         go install github.com/wailsapp/wails/v2/cmd/wails@latest

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v2
  #       with:
  #         # either 'goreleaser' (default) or 'goreleaser-pro'
  #         distribution: goreleaser
  #         version: latest
  #         args: release --rm-dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
